import { describe, expect, it, vi, beforeEach } from 'vitest';
import { fireEvent, render, screen } from '@testing-library/react';
import type { Fitting } from '@/core/schema';
import { useEntityStore } from '@/core/store/entityStore';
import { updateEntity as updateEntityCommand } from '@/core/commands/entityCommands';
import { FittingInspector } from '../FittingInspector';

vi.mock('@/core/commands/entityCommands', () => ({
  updateEntity: vi.fn(),
}));

function createFitting(): Fitting {
  return {
    id: 'fit-1',
    type: 'fitting',
    transform: { x: 0, y: 0, elevation: 0, rotation: 0, scaleX: 1, scaleY: 1 },
    zIndex: 10,
    createdAt: '2026-05-01T00:00:00.000Z',
    modifiedAt: '2026-05-01T00:00:00.000Z',
    props: {
      engineeringSystem: 'standard_duct',
      name: 'Elbow',
      fittingType: 'elbow_90',
      angle: 90,
      autoGenerated: false,
      autoInserted: false,
      manualOverride: false,
    },
    calculated: {
      equivalentLength: 0,
      pressureLoss: 0,
    },
  };
}

describe('FittingInspector', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    useEntityStore.getState().clearAllEntities();
  });

  it('lets elbow angle edits step by 5 degrees when selected', () => {
    const fitting = createFitting();
    useEntityStore.setState({ byId: { [fitting.id]: fitting }, allIds: [fitting.id] });

    render(<FittingInspector entity={fitting} />);

    const angleInput = screen.getByLabelText('Angle (deg)');
    expect(angleInput).toHaveAttribute('step', '1');

    fireEvent.change(screen.getByLabelText('Angle Step'), { target: { value: '5' } });

    expect(angleInput).toHaveAttribute('step', '5');

    fireEvent.change(angleInput, { target: { value: '47' } });

    expect(updateEntityCommand).toHaveBeenCalledTimes(1);
    const [, update] = vi.mocked(updateEntityCommand).mock.calls[0]!;
    expect((update.props as Fitting['props']).angle).toBe(45);
  });

  it('commits radius ratio, neck length, insulation, and end types from the new cards', () => {
    const fitting = createFitting();
    useEntityStore.setState({ byId: { [fitting.id]: fitting }, allIds: [fitting.id] });

    render(<FittingInspector entity={fitting} />);

    fireEvent.change(screen.getByTestId('fitting-radius-ratio'), { target: { value: '2.5' } });
    fireEvent.change(screen.getByLabelText('Neck length (in)'), { target: { value: '6' } });
    fireEvent.change(screen.getByLabelText('Insulated'), { target: { value: 'yes' } });
    fireEvent.change(screen.getByLabelText('Inlet'), { target: { value: 'flange' } });

    const calls = vi.mocked(updateEntityCommand).mock.calls;
    const committed = calls.map(([, update]) => update.props as Fitting['props']);
    expect(committed.some((props) => props.radiusRatio === 2.5)).toBe(true);
    expect(committed.some((props) => props.neckLength === 6)).toBe(true);
    expect(committed.some((props) => props.insulated === true)).toBe(true);
    expect(committed.some((props) => props.endTypeInlet === 'flange')).toBe(true);
  });
});
