import { describe, expect, it } from 'vitest';
import { MagneticConnectionService } from '../magneticConnectionService';
import type { Duct, Entity, Equipment, Fitting } from '@/core/schema';

function createDuct(id: string, x: number, y: number, rotation: number, length = 10): Duct {
  return {
    id,
    type: 'duct',
    transform: { x, y, elevation: 0, rotation, scaleX: 1, scaleY: 1 },
    zIndex: 5,
    createdAt: '2026-01-01T00:00:00.000Z',
    modifiedAt: '2026-01-01T00:00:00.000Z',
    props: {
      name: `Duct ${id}`,
      engineeringSystem: 'standard_duct',
      shape: 'round',
      diameter: 12,
      length,
      material: 'galvanized',
      airflow: 0,
      staticPressure: 0.1,
    },
    calculated: { area: 113, velocity: 0, frictionLoss: 0 },
  };
}

function createFitting(id: string, x: number, y: number): Fitting {
  return {
    id,
    type: 'fitting',
    transform: { x, y, elevation: 0, rotation: 0, scaleX: 1, scaleY: 1 },
    zIndex: 10,
    createdAt: '2026-01-01T00:00:00.000Z',
    modifiedAt: '2026-01-01T00:00:00.000Z',
    props: {
      engineeringSystem: 'standard_duct',
      fittingType: 'tee',
      autoGenerated: true,
      autoInserted: true,
      manualOverride: false,
      connectionPoints: [],
    },
    calculated: { equivalentLength: 0, pressureLoss: 0 },
  };
}

function createEquipment(id: string, x: number, y: number): Equipment {
  return {
    id,
    type: 'equipment',
    transform: { x, y, elevation: 0, rotation: 0, scaleX: 1, scaleY: 1 },
    zIndex: 5,
    createdAt: '2026-01-01T00:00:00.000Z',
    modifiedAt: '2026-01-01T00:00:00.000Z',
    props: {
      name: `Equipment ${id}`,
      engineeringSystem: 'standard_duct',
      equipmentType: 'fan',
      capacity: 1000,
      capacityUnit: 'CFM',
      staticPressure: 0.5,
      staticPressureUnit: 'in_wg',
      width: 24,
      depth: 24,
      height: 24,
      mountHeightUnit: 'in',
    },
  };
}

describe('MagneticConnectionService', () => {
  it('prefers duct endpoints over duct-body projections near a run end', () => {
    const entities: Record<string, Entity> = {
      duct: createDuct('duct', 100, 100, 0, 10),
    };

    const result = MagneticConnectionService.resolveSnapTarget(101, 100, entities);

    expect(result?.snapType).toBe('duct_endpoint');
    expect(result?.point).toEqual({ x: 100, y: 100 });
  });

  it('returns a duct-body snap for a valid mid-run projection', () => {
    const entities: Record<string, Entity> = {
      duct: createDuct('duct', 100, 100, 0, 10),
    };

    const result = MagneticConnectionService.resolveSnapTarget(160, 104, entities);

    expect(result?.snapType).toBe('duct_body');
    expect(result?.ductId).toBe('duct');
    expect(result?.point.x).toBeCloseTo(160, 3);
    expect(result?.point.y).toBeCloseTo(100, 3);
  });

  it('uses the documented snap priority across endpoints, fitting ports, and equipment points', () => {
    const entities: Record<string, Entity> = {
      duct: createDuct('duct', 100, 100, 0, 10),
      fitting: createFitting('fitting', 160, 140),
      equipment: createEquipment('equipment', 160, 140),
    };

    const endpointResult = MagneticConnectionService.resolveSnapTarget(101, 100, entities);
    const fittingResult = MagneticConnectionService.resolveSnapTarget(160, 140, entities);

    expect(endpointResult?.snapType).toBe('duct_endpoint');
    expect(fittingResult?.snapType).toBe('fitting_port');
  });
});
