import { describe, expect, it } from 'vitest';
import { MagneticConnectionService } from '../magneticConnectionService';
import type { Duct, Entity, Equipment, Fitting } from '@/core/schema';
import { createDuctRun } from '../../entities/ductRunDefaults';

function createDuct(id: string, x: number, y: number, rotation: number, length = 10): Duct {
  return {
    id,
    type: 'duct',
    transform: { x, y, elevation: 0, rotation, scaleX: 1, scaleY: 1 },
    zIndex: 5,
    createdAt: '2026-01-01T00:00:00.000Z',
    modifiedAt: '2026-01-01T00:00:00.000Z',
    props: {
      name: `Duct ${id}`,
      engineeringSystem: 'standard_duct',
      shape: 'round',
      diameter: 12,
      length,
      material: 'galvanized',
      airflow: 0,
      staticPressure: 0.1,
    },
    calculated: { area: 113, velocity: 0, frictionLoss: 0 },
  };
}

function createFitting(id: string, x: number, y: number, fittingType: Fitting['props']['fittingType'] = 'tee'): Fitting {
  return {
    id,
    type: 'fitting',
    transform: { x, y, elevation: 0, rotation: 0, scaleX: 1, scaleY: 1 },
    zIndex: 10,
    createdAt: '2026-01-01T00:00:00.000Z',
    modifiedAt: '2026-01-01T00:00:00.000Z',
    props: {
      engineeringSystem: 'standard_duct',
      fittingType,
      autoGenerated: true,
      autoInserted: true,
      manualOverride: false,
      connectionPoints: [],
    },
    calculated: { equivalentLength: 0, pressureLoss: 0 },
  };
}

function createEquipment(id: string, x: number, y: number): Equipment {
  return {
    id,
    type: 'equipment',
    transform: { x, y, elevation: 0, rotation: 0, scaleX: 1, scaleY: 1 },
    zIndex: 5,
    createdAt: '2026-01-01T00:00:00.000Z',
    modifiedAt: '2026-01-01T00:00:00.000Z',
    props: {
      name: `Equipment ${id}`,
      engineeringSystem: 'standard_duct',
      equipmentType: 'fan',
      capacity: 1000,
      capacityUnit: 'CFM',
      staticPressure: 0.5,
      staticPressureUnit: 'in_wg',
      width: 24,
      depth: 24,
      height: 24,
      mountHeightUnit: 'in',
    },
  };
}

function createRun(id: string, x: number, y: number, rotation: number, installLength = 10) {
  const run = createDuctRun({ x, y, installLength, sectionLengthOverride: 5 });
  run.id = id;
  run.transform.rotation = rotation;
  run.props.startPoint = { x, y };
  run.props.endPoint = { x: x + installLength * 12, y };
  return run;
}

describe('MagneticConnectionService', () => {
  it('prefers duct endpoints over duct-body projections near a run end', () => {
    const entities: Record<string, Entity> = {
      duct: createDuct('duct', 100, 100, 0, 10),
    };

    const result = MagneticConnectionService.resolveSnapTarget(101, 100, entities);

    expect(result?.snapType).toBe('duct_endpoint');
    expect(result?.point).toEqual({ x: 100, y: 100 });
  });

  it('returns a duct-body snap for a valid mid-run projection', () => {
    const entities: Record<string, Entity> = {
      duct: createDuct('duct', 100, 100, 0, 10),
    };

    const result = MagneticConnectionService.resolveSnapTarget(160, 111, entities);

    expect(result?.snapType).toBe('duct_body');
    expect(result?.ductId).toBe('duct');
    expect(result?.point.x).toBeCloseTo(160, 3);
    expect(result?.point.y).toBeCloseTo(100, 3);
  });

  it('returns magnetic targets near duct endpoints, sides, and edges', () => {
    const entities: Record<string, Entity> = {
      run: createRun('run', 100, 100, 0, 10),
    };

    const endpoint = MagneticConnectionService.resolveSnapTarget(101, 100, entities);
    const side = MagneticConnectionService.resolveSnapTarget(160, 108, entities);
    const edge = MagneticConnectionService.resolveSnapTarget(160, 112, entities);

    expect(endpoint?.snapType).toBe('duct_endpoint');
    expect(side?.snapType).toBe('duct_body');
    expect(side?.point).toEqual({ x: 160, y: 100 });
    expect(edge?.snapType).toBe('duct_body');
    expect(edge?.point).toEqual({ x: 160, y: 100 });
  });

  it('resolves duct_run endpoints and mid-run body projections', () => {
    const entities: Record<string, Entity> = {
      run: createRun('run', 100, 100, 0, 10),
    };

    const endpointResult = MagneticConnectionService.resolveSnapTarget(101, 100, entities);
    const bodyResult = MagneticConnectionService.resolveSnapTarget(160, 104, entities);

    expect(endpointResult?.snapType).toBe('duct_endpoint');
    expect(endpointResult?.entityType).toBe('duct_run');
    expect(bodyResult?.snapType).toBe('duct_body');
    expect(bodyResult?.ductId).toBe('run');
    expect(bodyResult?.entityType).toBe('duct_run');
  });

  it('uses the documented snap priority across endpoints, fitting ports, and equipment points', () => {
    const entities: Record<string, Entity> = {
      duct: createDuct('duct', 100, 100, 0, 10),
      fitting: createFitting('fitting', 160, 140),
      equipment: createEquipment('equipment', 160, 140),
    };

    const endpointResult = MagneticConnectionService.resolveSnapTarget(101, 100, entities);
    const fittingResult = MagneticConnectionService.resolveSnapTarget(128, 140, entities);

    expect(endpointResult?.snapType).toBe('duct_endpoint');
    expect(fittingResult?.snapType).toBe('fitting_port');
    expect(fittingResult?.fittingPortRole).toBe('inlet');
  });

  it('resolves reducer inlet and outlet fitting ports instead of the fitting center', () => {
    const entities: Record<string, Entity> = {
      fitting: createFitting('fitting', 200, 140, 'reducer'),
    };

    const inletResult = MagneticConnectionService.resolveSnapTarget(173, 140, entities);
    const outletResult = MagneticConnectionService.resolveSnapTarget(229, 140, entities);

    expect(inletResult).toMatchObject({
      snapType: 'fitting_port',
      point: { x: 172, y: 140 },
      fittingId: 'fitting',
      fittingPortRole: 'inlet',
    });
    expect(outletResult).toMatchObject({
      snapType: 'fitting_port',
      point: { x: 228, y: 140 },
      fittingId: 'fitting',
      fittingPortRole: 'outlet',
    });
  });

  it('applies fitting rotation when resolving inlet and outlet ports', () => {
    const fitting = createFitting('fitting', 200, 140, 'reducer');
    fitting.transform.rotation = 90;
    const entities: Record<string, Entity> = { fitting };

    const inletResult = MagneticConnectionService.resolveSnapTarget(200, 113, entities);
    const outletResult = MagneticConnectionService.resolveSnapTarget(200, 169, entities);

    expect(inletResult).toMatchObject({
      snapType: 'fitting_port',
      point: { x: 200, y: 112 },
      fittingPortRole: 'inlet',
    });
    expect(outletResult).toMatchObject({
      snapType: 'fitting_port',
      point: { x: 200, y: 168 },
      fittingPortRole: 'outlet',
    });
  });

  it('returns no magnetic target when the cursor is outside snap tolerance', () => {
    const entities: Record<string, Entity> = {
      duct: createDuct('duct', 100, 100, 0, 10),
    };

    const result = MagneticConnectionService.resolveSnapTarget(160, 140, entities);

    expect(result).toBeNull();
  });
});
