import { beforeEach, describe, expect, it, vi } from 'vitest';
import { fireEvent, render, screen } from '@testing-library/react';
import type { Duct, Fitting } from '@/core/schema';
import { useDuctOverlayStore } from '@/core/store/ductOverlayStore';
import { useEntityStore } from '@/core/store/entityStore';
import { useValidationStore } from '@/core/store/validationStore';
import { ValidationDashboard } from '../ValidationDashboard';

describe('ValidationDashboard duct color overlay', () => {
  beforeEach(() => {
    useDuctOverlayStore.getState().resetOverlay();
    useEntityStore.getState().clearAllEntities();
    useValidationStore.getState().clearAll();
  });

  it('shows overlay options and writes the session overlay mode', () => {
    render(<ValidationDashboard />);

    expect(screen.getByText('Duct Color Overlay')).toBeDefined();
    expect(screen.getByLabelText('Off')).toBeDefined();
    expect(screen.getByLabelText('By Velocity')).toBeDefined();
    expect(screen.getByLabelText('By Pressure')).toBeDefined();

    fireEvent.click(screen.getByLabelText('By Velocity'));
    expect(useDuctOverlayStore.getState().overlayMode).toBe('velocity');

    fireEvent.click(screen.getByLabelText('By Pressure'));
    expect(useDuctOverlayStore.getState().overlayMode).toBe('pressure');
  });

  it('shows the auto-fitting dry-run summary and reports conflict conversions', () => {
    const existing = duct('existing', 100, 100, 0);
    const next = duct('new', 220, 100, 90);
    const lockedConflict = fitting('fit-locked-conflict', 'existing', 'new', 'reducer');
    useEntityStore.setState({
      byId: {
        [existing.id]: existing,
        [next.id]: next,
        [lockedConflict.id]: lockedConflict,
      },
      allIds: [existing.id, next.id, lockedConflict.id],
    });
    const toast = vi.fn();
    window.addEventListener('sws:toast', toast);

    render(<ValidationDashboard />);

    expect(screen.getByText(/1 update planned/i)).toBeDefined();
    expect(screen.getByText(/1 conflict conversion/i)).toBeDefined();

    fireEvent.click(screen.getByTestId('rerun-autofitting'));

    expect(toast).toHaveBeenCalledWith(
      expect.objectContaining({
        detail: expect.objectContaining({
          message: expect.stringContaining('1 conflict converted'),
          type: 'success',
        }),
      })
    );
    window.removeEventListener('sws:toast', toast);
  });
});

function duct(id: string, x: number, y: number, rotation: number): Duct {
  return {
    id,
    type: 'duct',
    transform: { x, y, elevation: 0, rotation, scaleX: 1, scaleY: 1 },
    zIndex: 5,
    createdAt: '2026-01-01T00:00:00.000Z',
    modifiedAt: '2026-01-01T00:00:00.000Z',
    props: {
      engineeringSystem: 'standard_duct',
      name: `Duct ${id}`,
      shape: 'round',
      diameter: 12,
      length: 10,
      material: 'galvanized',
      airflow: 1000,
      staticPressure: 0.1,
    },
    calculated: { area: 113, velocity: 1200, frictionLoss: 0.05 },
  };
}

function fitting(id: string, inletDuctId: string, outletDuctId: string, fittingType: Fitting['props']['fittingType']): Fitting {
  return {
    id,
    type: 'fitting',
    transform: { x: 220, y: 100, elevation: 0, rotation: 0, scaleX: 1, scaleY: 1 },
    zIndex: 10,
    createdAt: '2026-01-01T00:00:00.000Z',
    modifiedAt: '2026-01-01T00:00:00.000Z',
    props: {
      engineeringSystem: 'standard_duct',
      name: `Fitting ${id}`,
      fittingType,
      inletDuctId,
      outletDuctId,
      autoGenerated: true,
      autoInserted: true,
      manualOverride: true,
    },
    calculated: { equivalentLength: 0, pressureLoss: 0 },
  };
}
