import { describe, expect, it } from 'vitest';
import type { Duct, Entity, Fitting } from '@/core/schema';
import {
  deriveDynamicFittingSymbol,
  formatInches,
  normalizeSize,
  sanitizeSize,
} from '../fittingSymbolModel';

function createDuct(id: string, overrides: Partial<Duct['props']>): Duct {
  const isRound = overrides.shape !== 'rectangular';

  return {
    id,
    type: 'duct',
    transform: { x: 0, y: 0, elevation: 0, rotation: 0, scaleX: 1, scaleY: 1 },
    zIndex: 0,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    props: {
      name: 'Test Duct',
      engineeringSystem: 'standard_duct',
      shape: isRound ? 'round' : 'rectangular',
      diameter: isRound ? 12 : undefined,
      width: isRound ? undefined : 24,
      height: isRound ? undefined : 12,
      length: 10,
      material: 'galvanized',
      airflow: 0,
      staticPressure: 0.1,
      ...overrides,
    } as Duct['props'],
    calculated: {
      area: 0,
      velocity: 0,
      frictionLoss: 0,
    },
    warnings: undefined,
  };
}

function createFitting(overrides: Partial<Fitting['props']>): Fitting {
  return {
    id: crypto.randomUUID(),
    type: 'fitting',
    transform: { x: 0, y: 0, elevation: 0, rotation: 0, scaleX: 1, scaleY: 1 },
    zIndex: 0,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    props: {
      manualOverride: false,
      engineeringSystem: 'standard_duct',
      fittingType: 'elbow_90',
      autoGenerated: false,
      autoInserted: false,
      manualOverride: false,
      ...overrides,
    } as Fitting['props'],
    calculated: {
      equivalentLength: 0,
      pressureLoss: 0,
    },
    warnings: undefined,
  };
}

describe('fittingSymbolModel', () => {
  it('sanitizes invalid sizes', () => {
    expect(sanitizeSize(Number.NaN)).toBe(1);
    expect(sanitizeSize(-3)).toBe(1);
  });

  it('normalizes sizes with safe minimums', () => {
    expect(normalizeSize(12, 12)).toBeGreaterThanOrEqual(10);
    expect(normalizeSize(0, 0)).toBeGreaterThanOrEqual(10);
  });

  it('formats inch labels', () => {
    expect(formatInches(12)).toBe('12"');
  });

  it('uses elbow angle to derive the elbow variant', () => {
    const inletDuct = createDuct('duct-a', { diameter: 14 });
    const fitting = createFitting({
      fittingType: 'elbow_90',
      angle: 45,
      inletDuctId: inletDuct.id,
    });
    const spec = deriveDynamicFittingSymbol(fitting, { [inletDuct.id]: inletDuct });

    expect(spec.kind).toBe('elbow_45');
    if (spec.kind !== 'elbow_45') {
      throw new Error('Expected elbow_45');
    }
    expect(spec.props.size).toBe(14);
  });

  it('prefers transition data for reducers', () => {
    const fitting = createFitting({
      fittingType: 'reducer',
      transitionData: {
        fromShape: 'round',
        toShape: 'round',
        fromDiameter: 18,
        toDiameter: 12,
      },
    });
    const spec = deriveDynamicFittingSymbol(fitting, {});

    expect(spec.kind).toBe('reducer');
    if (spec.kind !== 'reducer') {
      throw new Error('Expected reducer');
    }
    expect(spec.props.inletSize).toBe(18);
    expect(spec.props.outletSize).toBe(12);
  });

  it('derives branch sizes for tees from connected ducts', () => {
    const mainDuct = createDuct('duct-main', { diameter: 16 });
    const branchDuct = createDuct('duct-branch', { diameter: 10 });
    const fitting = createFitting({
      fittingType: 'tee',
      inletDuctId: mainDuct.id,
      outletDuctId: branchDuct.id,
    });
    const entitiesById: Record<string, Entity> = {
      [mainDuct.id]: mainDuct,
      [branchDuct.id]: branchDuct,
    };

    const spec = deriveDynamicFittingSymbol(fitting, entitiesById);

    expect(spec.kind).toBe('tee');
    if (spec.kind !== 'tee') {
      throw new Error('Expected tee');
    }
    expect(spec.props.mainSize).toBe(16);
    expect(spec.props.branchSize).toBe(10);
  });

  it('falls back predictably when fitting dimensions are missing', () => {
    const fitting = createFitting({
      fittingType: 'wye',
    });
    const spec = deriveDynamicFittingSymbol(fitting, {});

    expect(spec.kind).toBe('wye');
    if (spec.kind !== 'wye') {
      throw new Error('Expected wye');
    }
    expect(spec.props.mainSize).toBe(12);
    expect(spec.props.branchSize).toBe(9);
  });

  it('builds rect-to-round specs from transition data', () => {
    const fitting = createFitting({
      fittingType: 'transition_square_to_round',
      transitionData: {
        fromShape: 'rectangular',
        fromWidth: 24,
        fromHeight: 12,
        toShape: 'round',
        toDiameter: 14,
      },
    });
    const spec = deriveDynamicFittingSymbol(fitting, {});

    expect(spec.kind).toBe('rect_to_round');
    if (spec.kind !== 'rect_to_round') {
      throw new Error('Expected rect_to_round');
    }
    expect(spec.props.rectWidth).toBe(24);
    expect(spec.props.rectHeight).toBe(12);
    expect(spec.props.roundSize).toBe(14);
  });
});
