import { z } from 'zod';
import { BaseEntitySchema } from './base.schema';
import { ConstraintStatusSchema } from './duct.schema';

/**
 * Fitting types for duct connections
 */
export const FittingTypeSchema = z.enum([
  'elbow_90',
  'elbow_45',
  'tee',
  'reducer',
  'cap',
  'transition_square_to_round',
  'reducer_tapered',
  'reducer_eccentric',
  'wye',
  'elbow_mitered',
  'end_boot',
]);

export type FittingType = z.infer<typeof FittingTypeSchema>;

/**
 * Fitting properties
 * Added name field for consistency with other entity types
 */
export const FittingPropsSchema = z.object({
  name: z.string().min(1).max(100).optional().describe('Optional fitting name/label'),
  fittingType: FittingTypeSchema,
  angle: z.number().min(0).max(180).optional().describe('Angle in degrees (for elbows)'),
  inletDuctId: z.string().uuid().optional(),
  outletDuctId: z.string().uuid().optional(),
  
  // Service & Catalog references
  serviceId: z.string().uuid().optional().describe('Active Service ID'),
  catalogItemId: z.string().optional().describe('Resolved Catalog Item ID'),
  autoGenerated: z.boolean().optional().describe('Created automatically by connection tool'),

  // Phase 1 foundation fields for auto-fitting workflows
  autoInserted: z.boolean().optional().describe('Created automatically by fitting generation'),
  connectionPoints: z.array(z.object({
    ductId: z.string().uuid(),
    pointIndex: z.number().int().nonnegative().optional(),
  })).optional(),
  transitionData: z.object({
    fromShape: z.enum(['round', 'rectangular']).optional(),
    toShape: z.enum(['round', 'rectangular']).optional(),
    fromDiameter: z.number().positive().optional(),
    toDiameter: z.number().positive().optional(),
    fromWidth: z.number().positive().optional(),
    fromHeight: z.number().positive().optional(),
    toWidth: z.number().positive().optional(),
    toHeight: z.number().positive().optional(),
    alignment: z.enum(['center_line', 'flat_top', 'flat_bottom']).optional(),
  }).optional(),
  constraintStatus: ConstraintStatusSchema.optional(),
});

export type FittingProps = z.infer<typeof FittingPropsSchema>;

/**
 * Calculated fitting values
 */
export const FittingCalculatedSchema = z.object({
  equivalentLength: z.number().nonnegative().describe('Equivalent length in feet'),
  pressureLoss: z.number().nonnegative().describe('Pressure loss in in.w.g.'),
});

export type FittingCalculated = z.infer<typeof FittingCalculatedSchema>;

/**
 * Complete Fitting entity schema
 */
export const FittingSchema = BaseEntitySchema.extend({
  type: z.literal('fitting'),
  props: FittingPropsSchema,
  calculated: FittingCalculatedSchema,
  warnings: z.object({
    constraintViolations: z.array(z.string()).optional(),
  }).optional(),
});

export type Fitting = z.infer<typeof FittingSchema>;

/**
 * Default values for fittings by type
 */
export const DEFAULT_FITTING_PROPS: Record<FittingType, FittingProps> = {
  elbow_90: {
    fittingType: 'elbow_90',
    angle: 90,
    autoGenerated: false,
    autoInserted: false,
  },
  elbow_45: {
    fittingType: 'elbow_45',
    angle: 45,
    autoGenerated: false,
    autoInserted: false,
  },
  tee: {
    fittingType: 'tee',
    autoGenerated: false,
    autoInserted: false,
  },
  reducer: {
    fittingType: 'reducer',
    autoGenerated: false,
    autoInserted: false,
  },
  cap: {
    fittingType: 'cap',
    autoGenerated: false,
    autoInserted: false,
  },
  transition_square_to_round: {
    fittingType: 'transition_square_to_round',
    autoGenerated: false,
    autoInserted: false,
  },
  reducer_tapered: {
    fittingType: 'reducer_tapered',
    autoGenerated: false,
    autoInserted: false,
  },
  reducer_eccentric: {
    fittingType: 'reducer_eccentric',
    autoGenerated: false,
    autoInserted: false,
  },
  wye: {
    fittingType: 'wye',
    autoGenerated: false,
    autoInserted: false,
  },
  elbow_mitered: {
    fittingType: 'elbow_mitered',
    angle: 90,
    autoGenerated: false,
    autoInserted: false,
  },
  end_boot: {
    fittingType: 'end_boot',
    autoGenerated: false,
    autoInserted: false,
  },
};

/**
 * Default calculated values for a fitting
 */
export const DEFAULT_FITTING_CALCULATED: FittingCalculated = {
  equivalentLength: 0,
  pressureLoss: 0,
};

/**
 * Create default fitting props for a given type with optional name
 */
export function createDefaultFittingProps(type: FittingType, name?: string): FittingProps {
  return {
    ...DEFAULT_FITTING_PROPS[type],
    name: name ?? `New ${type.replace('_', ' ')}`,
  };
}
