import { z } from 'zod';
import { BaseEntitySchema, ServiceIdSchema } from './base.schema';
import { ConstraintStatusSchema } from './duct.schema';

/**
 * Fitting types for duct connections
 */
export const FittingTypeSchema = z.enum([
  'elbow_90',
  'elbow_45',
  'tee',
  'reducer',
  'cap',
  'transition_square_to_round',
  'reducer_tapered',
  'reducer_eccentric',
  'wye',
  'elbow_mitered',
  'end_boot',
]);

export type FittingType = z.infer<typeof FittingTypeSchema>;

export const FittingPortSchema = z.object({
  id: z.string().min(1),
  role: z.enum(['inlet', 'outlet', 'straight_out', 'branch_out']),
  direction: z.enum(['in', 'out']),
  connectedDuctRunId: z.string().uuid(),
  connectedEnd: z.enum(['start', 'end']),
});

export type FittingPort = z.infer<typeof FittingPortSchema>;

/**
 * Per-port end treatment. Drives the end-line decoration and (future)
 * fabrication notes. Optional so legacy projects load unchanged.
 */
export const FittingEndTypeSchema = z.enum(['raw', 'flange', 'crimped', 'coupled', 'slip_joint']);
export type FittingEndType = z.infer<typeof FittingEndTypeSchema>;

const SharedFittingPropsSchema = z.object({
  name: z.string().min(1).max(100).optional().describe('Optional fitting name/label'),
  fittingType: FittingTypeSchema,
  angle: z.number().min(0).max(180).optional().describe('Angle in degrees (for elbows)'),
  inletDuctId: z.string().uuid().optional(),
  outletDuctId: z.string().uuid().optional(),

  // Parametric geometry fields (see fittingGeometry.ts). All optional with
  // documented defaults so existing persisted projects load unchanged and
  // render through the new geometry system using safe fallbacks.
  radiusRatio: z
    .number()
    .min(0.5)
    .max(3.0)
    .optional()
    .describe('Elbow centerline radius / duct width (R/W). SMACNA default 1.5.'),
  neckLength: z
    .number()
    .min(0)
    .max(120)
    .optional()
    .describe('Straight throat/neck length at openings, inches.'),
  insulated: z.boolean().optional().describe('Whether the fitting carries external insulation'),
  insulationThickness: z
    .number()
    .min(0)
    .max(12)
    .optional()
    .describe('External insulation thickness, inches (when insulated).'),
  endTypeInlet: FittingEndTypeSchema.optional().describe('End treatment at the inlet opening'),
  endTypeOutlet: FittingEndTypeSchema.optional().describe('End treatment at the outlet opening'),
  
  // Service & Catalog references
  serviceId: ServiceIdSchema,
  catalogItemId: z.string().optional().describe('Resolved Catalog Item ID'),
  autoGenerated: z.boolean().optional().describe('Created automatically by connection tool'),

  // Phase 1 foundation fields for auto-fitting workflows
  autoInserted: z.boolean().optional().describe('Created automatically by fitting generation'),
  manualOverride: z
    .boolean()
    .optional()
    .default(false)
    .describe('Locked because the user manually edited an auto-inserted fitting'),
  connectionPoints: z.array(z.object({
    ductId: z.string().uuid(),
    pointIndex: z.number().int().nonnegative().optional(),
  })).optional(),
  ports: z.array(FittingPortSchema).optional(),
  transitionData: z.object({
    fromShape: z.enum(['round', 'rectangular']).optional(),
    toShape: z.enum(['round', 'rectangular']).optional(),
    fromDiameter: z.number().positive().optional(),
    toDiameter: z.number().positive().optional(),
    fromWidth: z.number().positive().optional(),
    fromHeight: z.number().positive().optional(),
    toWidth: z.number().positive().optional(),
    toHeight: z.number().positive().optional(),
    alignment: z.enum(['center_line', 'flat_top', 'flat_bottom']).optional(),
  }).optional(),
  constraintStatus: ConstraintStatusSchema.optional(),
});

export const StandardFittingPropsSchema = SharedFittingPropsSchema.extend({
  engineeringSystem: z.literal('standard_duct'),
});

/**
 * Fitting properties
 * Added name field for consistency with other entity types
 */
export const FittingPropsSchema = z.preprocess(
  (value) => {
    if (!value || typeof value !== 'object' || Array.isArray(value)) {
      return value;
    }

    const candidate = value as Record<string, unknown>;
    return {
      engineeringSystem: candidate.engineeringSystem ?? 'standard_duct',
      ...candidate,
    };
  },
  StandardFittingPropsSchema
);

export type FittingProps = z.infer<typeof FittingPropsSchema>;

/**
 * Calculated fitting values
 */
export const FittingCalculatedSchema = z.object({
  equivalentLength: z.number().nonnegative().describe('Equivalent length in feet'),
  pressureLoss: z.number().nonnegative().describe('Pressure loss in in.w.g.'),
  cumulativePressureDrop: z
    .number()
    .nonnegative()
    .optional()
    .describe('Total pressure loss from source equipment to this fitting in in.w.g.'),
  availableStaticPressure: z
    .number()
    .nonnegative()
    .optional()
    .describe('Remaining source static pressure at this fitting in in.w.g.'),
});

export type FittingCalculated = z.infer<typeof FittingCalculatedSchema>;

/**
 * Complete Fitting entity schema
 */
export const FittingSchema = BaseEntitySchema.extend({
  type: z.literal('fitting'),
  props: FittingPropsSchema,
  calculated: FittingCalculatedSchema,
  warnings: z.object({
    constraintViolations: z.array(z.string()).optional(),
  }).optional(),
});

export type Fitting = Omit<z.infer<typeof FittingSchema>, 'props'> & { props: FittingProps };

/**
 * Default values for fittings by type
 */
export const DEFAULT_FITTING_PROPS: Record<FittingType, FittingProps> = {
  elbow_90: {
    engineeringSystem: 'standard_duct',
    fittingType: 'elbow_90',
    angle: 90,
    autoGenerated: false,
    autoInserted: false,
    manualOverride: false,
  },
  elbow_45: {
    engineeringSystem: 'standard_duct',
    fittingType: 'elbow_45',
    angle: 45,
    autoGenerated: false,
    autoInserted: false,
    manualOverride: false,
  },
  tee: {
    engineeringSystem: 'standard_duct',
    fittingType: 'tee',
    autoGenerated: false,
    autoInserted: false,
    manualOverride: false,
  },
  reducer: {
    engineeringSystem: 'standard_duct',
    fittingType: 'reducer',
    autoGenerated: false,
    autoInserted: false,
    manualOverride: false,
  },
  cap: {
    engineeringSystem: 'standard_duct',
    fittingType: 'cap',
    autoGenerated: false,
    autoInserted: false,
    manualOverride: false,
  },
  transition_square_to_round: {
    engineeringSystem: 'standard_duct',
    fittingType: 'transition_square_to_round',
    autoGenerated: false,
    autoInserted: false,
    manualOverride: false,
  },
  reducer_tapered: {
    engineeringSystem: 'standard_duct',
    fittingType: 'reducer_tapered',
    autoGenerated: false,
    autoInserted: false,
    manualOverride: false,
  },
  reducer_eccentric: {
    engineeringSystem: 'standard_duct',
    fittingType: 'reducer_eccentric',
    autoGenerated: false,
    autoInserted: false,
    manualOverride: false,
  },
  wye: {
    engineeringSystem: 'standard_duct',
    fittingType: 'wye',
    autoGenerated: false,
    autoInserted: false,
    manualOverride: false,
  },
  elbow_mitered: {
    engineeringSystem: 'standard_duct',
    fittingType: 'elbow_mitered',
    angle: 90,
    autoGenerated: false,
    autoInserted: false,
    manualOverride: false,
  },
  end_boot: {
    engineeringSystem: 'standard_duct',
    fittingType: 'end_boot',
    autoGenerated: false,
    autoInserted: false,
    manualOverride: false,
  },
};

/**
 * Default calculated values for a fitting
 */
export const DEFAULT_FITTING_CALCULATED: FittingCalculated = {
  equivalentLength: 0,
  pressureLoss: 0,
};

/**
 * Create default fitting props for a given type with optional name
 */
export function createDefaultFittingProps(type: FittingType, name?: string): FittingProps {
  return {
    ...DEFAULT_FITTING_PROPS[type],
    name: name ?? `New ${type.replace('_', ' ')}`,
  };
}
