import { z } from 'zod';
import { BaseEntitySchema } from './base.schema';

/**
 * Fitting types for duct connections
 */
export const FittingTypeSchema = z.enum(['elbow_90', 'elbow_45', 'tee', 'reducer', 'cap']);

export type FittingType = z.infer<typeof FittingTypeSchema>;

/**
 * Fitting properties
 * Added name field for consistency with other entity types
 */
export const FittingPropsSchema = z.object({
  name: z.string().min(1).max(100).optional().describe('Optional fitting name/label'),
  fittingType: FittingTypeSchema,
  angle: z.number().min(0).max(180).optional().describe('Angle in degrees (for elbows)'),
  inletDuctId: z.string().uuid().optional(),
  outletDuctId: z.string().uuid().optional(),
  
  // Service & Catalog references
  serviceId: z.string().uuid().optional().describe('Active Service ID'),
  catalogItemId: z.string().optional().describe('Resolved Catalog Item ID'),
  autoGenerated: z.boolean().optional().describe('Created automatically by connection tool'),
});

export type FittingProps = z.infer<typeof FittingPropsSchema>;

/**
 * Calculated fitting values
 */
export const FittingCalculatedSchema = z.object({
  equivalentLength: z.number().nonnegative().describe('Equivalent length in feet'),
  pressureLoss: z.number().nonnegative().describe('Pressure loss in in.w.g.'),
});

export type FittingCalculated = z.infer<typeof FittingCalculatedSchema>;

/**
 * Complete Fitting entity schema
 */
export const FittingSchema = BaseEntitySchema.extend({
  type: z.literal('fitting'),
  props: FittingPropsSchema,
  calculated: FittingCalculatedSchema,
});

export type Fitting = z.infer<typeof FittingSchema>;

/**
 * Default values for fittings by type
 */
export const DEFAULT_FITTING_PROPS: Record<FittingType, FittingProps> = {
  elbow_90: {
    fittingType: 'elbow_90',
    angle: 90,
    autoGenerated: false,
  },
  elbow_45: {
    fittingType: 'elbow_45',
    angle: 45,
    autoGenerated: false,
  },
  tee: {
    fittingType: 'tee',
    autoGenerated: false,
  },
  reducer: {
    fittingType: 'reducer',
    autoGenerated: false,
  },
  cap: {
    fittingType: 'cap',
    autoGenerated: false,
  },
};

/**
 * Default calculated values for a fitting
 */
export const DEFAULT_FITTING_CALCULATED: FittingCalculated = {
  equivalentLength: 0,
  pressureLoss: 0,
};

/**
 * Create default fitting props for a given type with optional name
 */
export function createDefaultFittingProps(type: FittingType, name?: string): FittingProps {
  return {
    ...DEFAULT_FITTING_PROPS[type],
    name: name ?? `New ${type.replace('_', ' ')}`,
  };
}
