import { ProjectCostEstimate } from '../cost/costCalculationService';
import { BOMExportRow } from './bomExportService';

export interface PDFExportOptions {
  includeBOM: boolean;
  includePricing: boolean;
  includeCanvasSnapshot: boolean;
  includeEngineeringNotes: boolean;
  projectName: string;
  projectNumber?: string;
  clientName?: string;
  pageSize: 'letter' | 'a4';
}

/**
 * PDF Generator Service
 * 
 * Generates professional PDF reports for project documentation
 */
export class PDFGenerator {
  /**
   * Generate a complete project report as PDF
   * Note: This is a placeholder implementation. In production, use a library like jsPDF or Puppeteer.
   */
  static generateProjectReport(
    options: PDFExportOptions,
    bomRows?: BOMExportRow[],
    costEstimate?: ProjectCostEstimate
  ): Uint8Array {
    // Placeholder: Return empty PDF bytes
    // In production, this would use jsPDF or similar library
    const placeholder = new Uint8Array([0x25, 0x50, 0x44, 0x46]); // %PDF header
    
    console.log('Generating PDF report:', {
      project: options.projectName,
      includeBOM: options.includeBOM,
      includePricing: options.includePricing,
      bomItemCount: bomRows?.length,
      totalCost: costEstimate?.breakdown.totalCost,
    });
    
    return placeholder;
  }

  /**
   * Generate HTML content for PDF (for server-side rendering)
   */
  static generateHTMLContent(
    options: PDFExportOptions,
    bomRows?: BOMExportRow[],
    costEstimate?: ProjectCostEstimate
  ): string {
    const title = `${options.projectName} - Project Report`;
    const date = new Date().toLocaleDateString();
    
    let html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; }
    h1 { color: #333; border-bottom: 2px solid #007bff; padding-bottom: 10px; }
    h2 { color: #555; margin-top: 30px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
    th { background-color: #f5f5f5; font-weight: bold; }
    .summary { background-color: #f9f9f9; padding: 20px; border-radius: 5px; }
    .total { font-size: 1.2em; font-weight: bold; color: #007bff; }
    .footer { margin-top: 50px; font-size: 0.8em; color: #999; }
  </style>
</head>
<body>
  <h1>${options.projectName}</h1>
  <div class="summary">
    <p><strong>Project Number:</strong> ${options.projectNumber || 'N/A'}</p>
    <p><strong>Client:</strong> ${options.clientName || 'N/A'}</p>
    <p><strong>Date:</strong> ${date}</p>
    <p><strong>Page Size:</strong> ${options.pageSize.toUpperCase()}</p>
  </div>
`;

    if (options.includeBOM && bomRows && bomRows.length > 0) {
      html += this.generateBOMSection(bomRows, options.includePricing);
    }

    if (costEstimate) {
      html += this.generateCostSection(costEstimate);
    }

    html += `
  <div class="footer">
    <p>Generated by SizeWise HVAC Canvas on ${date}</p>
  </div>
</body>
</html>`;

    return html;
  }

  private static generateBOMSection(rows: BOMExportRow[], includePricing: boolean): string {
    let html = `
  <h2>Bill of Materials</h2>
  <table>
    <thead>
      <tr>
        <th>Category</th>
        <th>Description</th>
        <th>Quantity</th>
        <th>Unit</th>
        <th>Size</th>
        ${includePricing ? '<th>Material Cost</th><th>Total Cost</th>' : ''}
      </tr>
    </thead>
    <tbody>
`;

    for (const row of rows) {
      html += `      <tr>
        <td>${row.category}</td>
        <td>${row.description}</td>
        <td>${row.quantity}</td>
        <td>${row.unit}</td>
        <td>${row.size || '-'}</td>
        ${includePricing ? `<td>$${row.materialCost?.toFixed(2) || '0.00'}</td><td>$${row.totalCost?.toFixed(2) || '0.00'}</td>` : ''}
      </tr>
`;
    }

    html += `    </tbody>
  </table>
`;

    return html;
  }

  private static generateCostSection(estimate: ProjectCostEstimate): string {
    const b = estimate.breakdown;
    
    return `
  <h2>Cost Summary</h2>
  <div class="summary">
    <p><strong>Material Cost:</strong> $${b.materialCost.toFixed(2)}</p>
    <p><strong>Labor Cost:</strong> $${b.laborCost.toFixed(2)}</p>
    <p><strong>Subtotal:</strong> $${b.subtotal.toFixed(2)}</p>
    <p><strong>Markup:</strong> $${b.markup.toFixed(2)}</p>
    <p><strong>Tax:</strong> $${b.tax.toFixed(2)}</p>
    <p class="total"><strong>Total Cost:</strong> $${b.totalCost.toFixed(2)}</p>
  </div>
`;
  }
}

export const pdfGenerator = new PDFGenerator();
