import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { Equipment } from '@/core/schema';
import type { FittingType } from '@/core/schema/fitting.schema';
import { FittingGenerationService } from '@/core/services/fittingGeneration';
import { fittingInsertionService } from '@/core/services/automation/fittingInsertionService';
import { useEntityStore } from '@/core/store/entityStore';
import { createDuctRun, resetDuctRunCounter } from '../../entities/ductRunDefaults';
import { createFitting, resetFittingCounter } from '../../entities/fittingDefaults';
import { DuctRunGeometryService } from '../../services/DuctRunGeometryService';
import { MagneticConnectionService } from '../../services/magneticConnectionService';
import { useSelectionStore } from '../../store/selectionStore';
import { getAngleDegrees } from '../angleConstraint';
import { DuctTool } from '../DuctTool';
import { SelectTool } from '../SelectTool';

describe('SelectTool duct_run segment selection', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
    useEntityStore.getState().clearAllEntities();
    useSelectionStore.getState().clearSelection();
    useSelectionStore.getState().setHovered(null);
    resetDuctRunCounter();
    resetFittingCounter();
    DuctTool.setAutoFittingEnabled(false);
  });

  function seedRun() {
    const run = createDuctRun({ x: 100, y: 100, installLength: 10, sectionLengthOverride: 5 });
    run.props.segments = [
      { index: 0, startStation: 0, endStation: 5, length: 5, isPartial: false },
      { index: 1, startStation: 5, endStation: 10, length: 5, isPartial: false },
    ];
    useEntityStore.getState().addEntity(run);
    return run;
  }

  function seedRunAt(id: string, x: number, y: number, installLength = 10) {
    const run = createDuctRun({ x, y, installLength, sectionLengthOverride: 5 });
    run.id = id;
    run.props.startPoint = { x, y };
    run.props.endPoint = { x: x + installLength * 12, y };
    useEntityStore.getState().addEntity(run);
    return run;
  }

  function seedAirHandlerAt(id: string, x: number, y: number): Equipment {
    const equipment: Equipment = {
      id,
      type: 'equipment',
      transform: { x, y, elevation: 0, rotation: 0, scaleX: 1, scaleY: 1 },
      zIndex: 20,
      createdAt: '2026-01-01T00:00:00.000Z',
      modifiedAt: '2026-01-01T00:00:00.000Z',
      props: {
        name: 'AHU-1',
        engineeringSystem: 'standard_duct',
        equipmentType: 'air_handler',
        capacity: 1000,
        capacityUnit: 'CFM',
        staticPressure: 1,
        staticPressureUnit: 'in_wg',
        width: 60,
        depth: 48,
        height: 96,
        mountHeightUnit: 'in',
        connectionPorts: [
          { id: 'supply-1', role: 'supply', edge: 'east', offsetRatio: 0.3, label: 'Supply' },
          { id: 'return-1', role: 'return', edge: 'west', offsetRatio: 0.3, label: 'Return' },
        ],
      },
    };
    useEntityStore.getState().addEntity(equipment);
    return equipment;
  }

  function seedRunBetween(
    id: string,
    start: { x: number; y: number },
    end: { x: number; y: number }
  ) {
    const lengthPx = Math.hypot(end.x - start.x, end.y - start.y);
    const run = createDuctRun({
      x: start.x,
      y: start.y,
      installLength: lengthPx / 12,
      sectionLengthOverride: 5,
    });
    run.id = id;
    run.transform.rotation = Math.atan2(end.y - start.y, end.x - start.x) * (180 / Math.PI);
    run.props.startPoint = start;
    run.props.endPoint = end;
    useEntityStore.getState().addEntity(run);
    return run;
  }

  function seedFittingAt(
    id: string,
    x: number,
    y: number,
    ductIds: string[],
    fittingType: FittingType = 'tee'
  ) {
    const fitting = createFitting(fittingType, {
      x,
      y,
      autoGenerated: true,
      autoInserted: true,
      connectionPoints: ductIds.map((ductId) => ({ ductId })),
    });
    fitting.id = id;
    useEntityStore.getState().addEntity(fitting);
    return fitting;
  }

  function seedThreeConnectedRuns() {
    const left = seedRunAt('left-run', -20, 100, 10);
    const middle = seedRunAt('middle-run', 100, 100, 10);
    const right = seedRunAt('right-run', 220, 100, 10);
    const startFitting = seedFittingAt('middle-start-fitting', 100, 100, [left.id, middle.id]);
    const endFitting = seedFittingAt('middle-end-fitting', 220, 100, [middle.id, right.id]);

    return { left, middle, right, startFitting, endFitting };
  }

  function seedThreeDuctBranchNetwork() {
    const left = seedRunBetween('branch-left-run', { x: 0, y: 100 }, { x: 100, y: 100 });
    const middle = seedRunBetween('branch-middle-run', { x: 100, y: 100 }, { x: 220, y: 100 });
    const branch = seedRunBetween('branch-vertical-run', { x: 100, y: 100 }, { x: 100, y: 220 });
    const tee = seedFittingAt('branch-tee', 100, 100, [left.id, middle.id, branch.id], 'tee');

    return { left, middle, branch, tee };
  }

  it('selects the run and hit section on first click', () => {
    const run = seedRun();
    const tool = new SelectTool();

    tool.onMouseDown({ x: 120, y: 100, button: 0 });
    tool.onMouseUp({ x: 120, y: 100, button: 0 });
    expect(useSelectionStore.getState().selectedIds).toEqual([run.id]);
    expect(useSelectionStore.getState().selectedSegments).toEqual([
      { runId: run.id, segmentIndex: 0 },
    ]);
  });

  it('adds segment selections with modifier clicks without dropping the parent run', () => {
    const run = seedRun();
    const tool = new SelectTool();

    useSelectionStore.getState().select(run.id);

    tool.onMouseDown({ x: 120, y: 100, button: 0 });
    tool.onMouseUp({ x: 120, y: 100, button: 0 });
    tool.onMouseDown({ x: 190, y: 100, button: 0, shiftKey: true });
    tool.onMouseUp({ x: 190, y: 100, button: 0, shiftKey: true });

    expect(useSelectionStore.getState().selectedIds).toEqual([run.id]);
    expect(useSelectionStore.getState().selectedSegments).toEqual([
      { runId: run.id, segmentIndex: 0 },
      { runId: run.id, segmentIndex: 1 },
    ]);
  });

  it('clears run and segment selection on empty-canvas click', () => {
    const run = seedRun();
    const tool = new SelectTool();

    useSelectionStore.getState().select(run.id);
    useSelectionStore.getState().selectSegment(run.id, 0);

    tool.onMouseDown({ x: 400, y: 400, button: 0 });
    tool.onMouseUp({ x: 400, y: 400, button: 0 });

    expect(useSelectionStore.getState().selectedIds).toEqual([]);
    expect(useSelectionStore.getState().selectedSegments).toEqual([]);
  });

  it('keeps duct_run endpoint props in sync when nudged with arrow keys', () => {
    const run = seedRun();
    const initialGeometry = DuctRunGeometryService.getGeometry(run);
    const tool = new SelectTool();
    useSelectionStore.getState().select(run.id);

    tool.onKeyDown({
      key: 'ArrowRight',
      code: 'ArrowRight',
      shiftKey: false,
      ctrlKey: false,
      altKey: false,
      repeat: false,
    });

    const updated = useEntityStore.getState().byId[run.id];
    expect(updated?.type).toBe('duct_run');
    if (updated?.type !== 'duct_run') {
      throw new Error('Expected duct_run');
    }
    expect(updated.transform.x).toBe(run.transform.x + 1);
    expect(updated.props.startPoint?.x).toBe(initialGeometry.start.x + 1);
    expect(updated.props.endPoint?.x).toBe(initialGeometry.end.x + 1);
  });

  it('waits for the drag threshold before detaching a middle duct body, then detaches both ends', () => {
    const { middle, startFitting, endFitting } = seedThreeConnectedRuns();
    const tool = new SelectTool();

    tool.onMouseDown({ x: 160, y: 100, button: 0 });
    tool.onMouseMove({ x: 163, y: 100, button: 0 });

    expect(useEntityStore.getState().byId[startFitting.id]).toBeDefined();
    expect(useEntityStore.getState().byId[endFitting.id]).toBeDefined();
    expect(useEntityStore.getState().byId[middle.id]?.transform.x).toBe(100);

    tool.onMouseMove({ x: 166, y: 100, button: 0 });
    tool.onMouseMove({ x: 172, y: 100, button: 0 });

    expect(useEntityStore.getState().byId[startFitting.id]).toBeUndefined();
    expect(useEntityStore.getState().byId[endFitting.id]).toBeUndefined();
    expect(useEntityStore.getState().byId[middle.id]?.transform.x).toBe(106);
  });

  it('does not detach a connected duct on mouse down alone', () => {
    const { middle, startFitting, endFitting } = seedThreeConnectedRuns();
    const tool = new SelectTool();

    tool.onMouseDown({ x: 160, y: 100, button: 0 });
    tool.onMouseUp({ x: 160, y: 100, button: 0 });

    expect(useEntityStore.getState().byId[startFitting.id]).toBeDefined();
    expect(useEntityStore.getState().byId[endFitting.id]).toBeDefined();
    expect(useEntityStore.getState().byId[middle.id]?.transform.x).toBe(100);
  });

  it('keeps a dragged connected duct detached on release near its original connection', () => {
    const { middle } = seedThreeConnectedRuns();
    const tool = new SelectTool();

    tool.onMouseDown({ x: 160, y: 100, button: 0 });
    tool.onMouseMove({ x: 166, y: 100, button: 0 });
    tool.onMouseMove({ x: 172, y: 100, button: 0 });
    tool.onMouseUp({ x: 172, y: 100, button: 0 });

    const moved = useEntityStore.getState().byId[middle.id];
    expect(moved?.type).toBe('duct_run');
    if (moved?.type !== 'duct_run') {
      throw new Error('Expected duct_run');
    }

    expect(moved.transform.x).toBe(106);
    expect(DuctRunGeometryService.getGeometry(moved).start).toEqual({ x: 106, y: 100 });
    expect(DuctRunGeometryService.getGeometry(moved).end).toEqual({ x: 226, y: 100 });
  });

  it('dragging a selected magnetic endpoint detaches only that endpoint fitting', () => {
    const { middle, startFitting, endFitting } = seedThreeConnectedRuns();
    const tool = new SelectTool();
    useSelectionStore.getState().select(middle.id);

    tool.onMouseDown({ x: 100, y: 100, button: 0 });
    tool.onMouseMove({ x: 88, y: 100, button: 0 });

    expect(useEntityStore.getState().byId[startFitting.id]).toBeUndefined();
    expect(useEntityStore.getState().byId[endFitting.id]).toBeDefined();
  });

  it('does not auto-remove a manual override fitting during endpoint detachment', () => {
    const { middle, startFitting, endFitting } = seedThreeConnectedRuns();
    useEntityStore.getState().updateEntity(startFitting.id, {
      props: {
        ...startFitting.props,
        manualOverride: true,
      },
    });
    const tool = new SelectTool();
    useSelectionStore.getState().select(middle.id);

    tool.onMouseDown({ x: 100, y: 100, button: 0 });
    tool.onMouseMove({ x: 88, y: 100, button: 0 });

    expect(useEntityStore.getState().byId[startFitting.id]).toBeDefined();
    expect(useEntityStore.getState().byId[endFitting.id]).toBeDefined();
  });

  it('leaves non-selected connected duct sections in place during selected endpoint detachment', () => {
    const { left, middle, right, startFitting, endFitting } = seedThreeConnectedRuns();
    const tool = new SelectTool();
    useSelectionStore.getState().select(middle.id);

    tool.onMouseDown({ x: 100, y: 100, button: 0 });
    tool.onMouseMove({ x: 88, y: 100, button: 0 });

    expect(useEntityStore.getState().byId[startFitting.id]).toBeUndefined();
    expect(useEntityStore.getState().byId[endFitting.id]).toBeDefined();
    expect(useEntityStore.getState().byId[left.id]?.transform.x).toBe(-20);
    expect(useEntityStore.getState().byId[right.id]?.transform.x).toBe(220);
  });

  it('lets a connected endpoint break away before leaving the magnetic snap radius', () => {
    const { middle } = seedThreeConnectedRuns();
    const tool = new SelectTool();
    useSelectionStore.getState().select(middle.id);

    tool.onMouseDown({ x: 104, y: 100, button: 0 });
    tool.onMouseMove({ x: 112, y: 100, button: 0 });
    tool.onMouseUp({ x: 112, y: 100, button: 0 });

    const moved = useEntityStore.getState().byId[middle.id];
    expect(moved?.type).toBe('duct_run');
    if (moved?.type !== 'duct_run') {
      throw new Error('Expected duct_run');
    }

    expect(DuctRunGeometryService.getGeometry(moved).start).toEqual({ x: 112, y: 100 });
    expect(DuctRunGeometryService.getGeometry(moved).end).toEqual({ x: 220, y: 100 });
  });

  it('updates the authored centerline when stretching a duct_run endpoint', () => {
    const { middle } = seedThreeConnectedRuns();
    const tool = new SelectTool();
    useSelectionStore.getState().select(middle.id);

    tool.onMouseDown({ x: 220, y: 100, button: 0 });
    tool.onMouseMove({ x: 220, y: 130, button: 0 });

    const stretched = useEntityStore.getState().byId[middle.id];
    expect(stretched?.type).toBe('duct_run');
    if (stretched?.type !== 'duct_run') {
      throw new Error('Expected duct_run');
    }

    expect(stretched.props.startPoint).toEqual({ x: 100, y: 100 });
    expect(getAngleDegrees(stretched.props.startPoint!, stretched.props.endPoint!)).toBeCloseTo(
      15,
      6
    );
    expect(stretched.props.designStartPoint).toEqual({ x: 100, y: 100 });
    expect(
      getAngleDegrees(stretched.props.designStartPoint!, stretched.props.designEndPoint!)
    ).toBeCloseTo(15, 6);
  });

  it('uses 1 degree angle steps while Shift-stretching a free duct_run endpoint', () => {
    const run = seedRunBetween('free-run', { x: 100, y: 100 }, { x: 220, y: 100 });
    const tool = new SelectTool();
    useSelectionStore.getState().select(run.id);

    tool.onMouseDown({ x: 220, y: 100, button: 0 });
    tool.onMouseMove({ x: 220, y: 130, button: 0, shiftKey: true });

    const stretched = useEntityStore.getState().byId[run.id];
    expect(stretched?.type).toBe('duct_run');
    if (stretched?.type !== 'duct_run') {
      throw new Error('Expected duct_run');
    }

    expect(getAngleDegrees(stretched.props.startPoint!, stretched.props.endPoint!)).toBeCloseTo(
      14,
      6
    );
  });

  it('recalculates an anchored auto-fitting after stretching the opposite free endpoint', () => {
    DuctTool.setAutoFittingEnabled(true);
    const trunk = seedRunBetween('trunk-run', { x: -20, y: 100 }, { x: 100, y: 100 });
    const branch = seedRunBetween('branch-run', { x: 100, y: 100 }, { x: 220, y: 100 });
    const elbow = seedFittingAt('corner-elbow', 100, 100, [trunk.id, branch.id], 'elbow_90');
    const tool = new SelectTool();
    useSelectionStore.getState().select(branch.id);

    tool.onMouseDown({ x: 220, y: 100, button: 0 });
    tool.onMouseMove({ x: 220, y: 220, button: 0 });
    tool.onMouseUp({ x: 220, y: 220, button: 0 });

    const stretched = useEntityStore.getState().byId[branch.id];
    const updatedFitting = useEntityStore.getState().byId[elbow.id];
    expect(stretched?.type).toBe('duct_run');
    expect(updatedFitting?.type).toBe('fitting');
    if (stretched?.type !== 'duct_run' || updatedFitting?.type !== 'fitting') {
      throw new Error('Expected duct_run and fitting');
    }

    expect(getAngleDegrees(stretched.props.startPoint!, stretched.props.endPoint!)).toBeCloseTo(
      45,
      6
    );
    expect(
      getAngleDegrees(stretched.props.designStartPoint!, stretched.props.designEndPoint!)
    ).toBeCloseTo(45, 6);
    expect(updatedFitting.props.angle).not.toBe(90);
  });

  it('keeps the connected centerline corner fixed when stretching only the opposite free endpoint', () => {
    DuctTool.setAutoFittingEnabled(true);
    const trunk = seedRunBetween('trunk-run', { x: -20, y: 100 }, { x: 100, y: 100 });
    const branch = seedRunBetween('cutback-branch', { x: 112, y: 100 }, { x: 220, y: 100 });
    useEntityStore.getState().updateEntity(branch.id, {
      props: {
        ...branch.props,
        designStartPoint: { x: 100, y: 100 },
        designEndPoint: { x: 220, y: 100 },
        designLength: 10,
      },
    });
    seedFittingAt('corner-elbow', 100, 100, [trunk.id, branch.id], 'elbow_90');

    const tool = new SelectTool();
    useSelectionStore.getState().select(branch.id);

    tool.onMouseDown({ x: 220, y: 100, button: 0 });
    tool.onMouseMove({ x: 220, y: 220, button: 0 });
    tool.onMouseUp({ x: 220, y: 220, button: 0 });

    const stretched = useEntityStore.getState().byId[branch.id];
    expect(stretched?.type).toBe('duct_run');
    if (stretched?.type !== 'duct_run') {
      throw new Error('Expected duct_run');
    }

    expect(stretched.props.designStartPoint).toEqual({ x: 100, y: 100 });
    expect(
      getAngleDegrees(stretched.props.designStartPoint!, stretched.props.designEndPoint!)
    ).toBeCloseTo(45, 6);
  });

  it('rebuilds auto-fittings through the topology-aware path after dragging a branch duct', () => {
    DuctTool.setAutoFittingEnabled(true);
    const buildReRunPlanSpy = vi
      .spyOn(fittingInsertionService, 'buildReRunPlan')
      .mockReturnValue({ changes: [], preservedManualOverrideCount: 0 });
    const resolveReRunPlanSpy = vi
      .spyOn(fittingInsertionService, 'resolveReRunPlan')
      .mockReturnValue({
        insertedOrUpdatedCount: 0,
        insertedCount: 0,
        updatedCount: 0,
        removedCount: 0,
        manualOverridesPreserved: 0,
        skippedChangedCount: 0,
        operations: [],
      });
    const legacyAutoGenerateSpy = vi
      .spyOn(FittingGenerationService, 'autoGenerateFittings')
      .mockReturnValue([]);
    const { middle } = seedThreeDuctBranchNetwork();
    const tool = new SelectTool();
    useSelectionStore.getState().select(middle.id);

    tool.onMouseDown({ x: 160, y: 100, button: 0 });
    tool.onMouseMove({ x: 166, y: 100, button: 0 });
    tool.onMouseMove({ x: 172, y: 100, button: 0 });
    tool.onMouseUp({ x: 172, y: 100, button: 0 });

    expect(buildReRunPlanSpy).toHaveBeenCalledTimes(1);
    expect(resolveReRunPlanSpy).toHaveBeenCalledTimes(1);
    expect(resolveReRunPlanSpy).toHaveBeenCalledWith(
      { changes: [], preservedManualOverrideCount: 0 },
      expect.objectContaining({
        [middle.id]: expect.objectContaining({ type: 'duct_run' }),
      })
    );
    expect(legacyAutoGenerateSpy).not.toHaveBeenCalled();
  });

  it('starts endpoint detachment in one drag when the pointer begins on a tee fitting', () => {
    const { middle, startFitting, endFitting } = seedThreeConnectedRuns();
    const tool = new SelectTool();

    tool.onMouseDown({ x: 100, y: 100, button: 0 });
    tool.onMouseMove({ x: 106, y: 100, button: 0 });
    tool.onMouseUp({ x: 106, y: 100, button: 0 });

    const moved = useEntityStore.getState().byId[middle.id];
    expect(moved?.type).toBe('duct_run');
    if (moved?.type !== 'duct_run') {
      throw new Error('Expected duct_run');
    }

    expect(useEntityStore.getState().byId[startFitting.id]).toBeUndefined();
    expect(useEntityStore.getState().byId[endFitting.id]).toBeDefined();
    expect(useSelectionStore.getState().selectedIds).toEqual([middle.id]);
    expect(DuctRunGeometryService.getGeometry(moved).start).toEqual({ x: 106, y: 100 });
    expect(DuctRunGeometryService.getGeometry(moved).end).toEqual({ x: 220, y: 100 });
  });

  it('starts endpoint detachment in one drag from an angled elbow fitting', () => {
    const horizontal = seedRunBetween('horizontal-run', { x: -20, y: 100 }, { x: 100, y: 100 });
    const vertical = seedRunBetween('vertical-run', { x: 100, y: 100 }, { x: 100, y: 220 });
    const elbow = seedFittingAt('corner-elbow', 100, 100, [horizontal.id, vertical.id], 'elbow_90');
    const tool = new SelectTool();

    tool.onMouseDown({ x: 100, y: 104, button: 0 });
    tool.onMouseMove({ x: 100, y: 112, button: 0 });
    tool.onMouseUp({ x: 100, y: 112, button: 0 });

    const moved = useEntityStore.getState().byId[vertical.id];
    expect(moved?.type).toBe('duct_run');
    if (moved?.type !== 'duct_run') {
      throw new Error('Expected duct_run');
    }

    expect(useEntityStore.getState().byId[elbow.id]).toBeUndefined();
    expect(useSelectionStore.getState().selectedIds).toEqual([vertical.id]);
    expect(DuctRunGeometryService.getGeometry(moved).start).toEqual({ x: 100, y: 112 });
    expect(DuctRunGeometryService.getGeometry(moved).end).toEqual({ x: 100, y: 220 });
  });

  it('starts endpoint detachment from the visible elbow body beside the duct centerline', () => {
    const horizontal = seedRunBetween('horizontal-run', { x: -20, y: 100 }, { x: 100, y: 100 });
    const vertical = seedRunBetween('vertical-run', { x: 100, y: 100 }, { x: 100, y: 220 });
    const elbow = seedFittingAt('corner-elbow', 100, 100, [horizontal.id, vertical.id], 'elbow_90');
    const tool = new SelectTool();

    tool.onMouseDown({ x: 88, y: 100, button: 0 });
    tool.onMouseMove({ x: 70, y: 100, button: 0 });
    tool.onMouseUp({ x: 70, y: 100, button: 0 });

    const moved = useEntityStore.getState().byId[horizontal.id];
    expect(moved?.type).toBe('duct_run');
    if (moved?.type !== 'duct_run') {
      throw new Error('Expected duct_run');
    }

    expect(useEntityStore.getState().byId[elbow.id]).toBeUndefined();
    expect(useSelectionStore.getState().selectedIds).toEqual([horizontal.id]);
    expect(DuctRunGeometryService.getGeometry(moved).start).toEqual({ x: -20, y: 100 });
    expect(DuctRunGeometryService.getGeometry(moved).end).toEqual({ x: 70, y: 100 });
  });

  it('does not snap a dragged duct until mouse release, then centers on the magnetic target', () => {
    const dragged = seedRunAt('dragged-run', 0, 100, 10);
    seedRunAt('target-run', 300, 100, 10);
    const tool = new SelectTool();
    useSelectionStore.getState().select(dragged.id);

    tool.onMouseDown({ x: 60, y: 100, button: 0 });
    tool.onMouseMove({ x: 66, y: 100, button: 0 });
    tool.onMouseMove({ x: 234, y: 100, button: 0 });

    const beforeRelease = useEntityStore.getState().byId[dragged.id];
    expect(beforeRelease?.type).toBe('duct_run');
    if (beforeRelease?.type !== 'duct_run') {
      throw new Error('Expected duct_run before release');
    }
    expect(DuctRunGeometryService.getGeometry(beforeRelease).end).toEqual({ x: 288, y: 100 });

    tool.onMouseUp({ x: 234, y: 100, button: 0 });

    const afterRelease = useEntityStore.getState().byId[dragged.id];
    expect(afterRelease?.type).toBe('duct_run');
    if (afterRelease?.type !== 'duct_run') {
      throw new Error('Expected duct_run after release');
    }
    expect(DuctRunGeometryService.getGeometry(afterRelease).end).toEqual({ x: 300, y: 100 });
  });

  it('attaches dragged reducer inlet and outlet ports to duct endpoints on release', () => {
    // Parametric reducer ports sit at ±25.2 (bodyLength(12)/2), so the runs meet
    // the openings at 174.8 / 225.2 for a clean dual attachment at origin 200.
    const inletRun = seedRunBetween('inlet-run', { x: 52, y: 100 }, { x: 174.8, y: 100 });
    const outletRun = seedRunBetween('outlet-run', { x: 225.2, y: 100 }, { x: 348, y: 100 });
    const reducer = seedFittingAt('dragged-reducer', 220, 100, [], 'reducer');
    const tool = new SelectTool();
    useSelectionStore.getState().select(reducer.id);

    tool.onMouseDown({ x: 220, y: 100, button: 0 });
    tool.onMouseMove({ x: 214, y: 100, button: 0 });
    tool.onMouseMove({ x: 194, y: 100, button: 0 });

    const beforeRelease = useEntityStore.getState().byId[reducer.id];
    expect(beforeRelease?.type).toBe('fitting');
    if (beforeRelease?.type !== 'fitting') {
      throw new Error('Expected fitting before release');
    }
    expect(beforeRelease.props.inletDuctId).toBeUndefined();
    expect(beforeRelease.props.outletDuctId).toBeUndefined();

    tool.onMouseUp({ x: 194, y: 100, button: 0 });

    const afterRelease = useEntityStore.getState().byId[reducer.id];
    expect(afterRelease?.type).toBe('fitting');
    if (afterRelease?.type !== 'fitting') {
      throw new Error('Expected fitting after release');
    }
    expect(afterRelease.transform.x).toBe(200);
    expect(afterRelease.transform.y).toBe(100);
    expect(afterRelease.props.inletDuctId).toBe(inletRun.id);
    expect(afterRelease.props.outletDuctId).toBe(outletRun.id);
    // Ports now align exactly with the run endpoints, so the committed
    // reconciliation records explicit port indices (PR-2/PR-8 contract).
    expect(afterRelease.props.connectionPoints).toEqual([
      { ductId: inletRun.id, pointIndex: 0 },
      { ductId: outletRun.id, pointIndex: 1 },
    ]);
  });

  it('aligns dragged equipment ports to duct endpoints and persists connection metadata', () => {
    const equipment = seedAirHandlerAt('equipment-1', 100, 100);
    const run = seedRunAt('target-run', 200, 114.4, 10);
    const tool = new SelectTool();

    tool.onMouseDown({ x: 130, y: 120, button: 0 });
    tool.onMouseMove({ x: 136, y: 120, button: 0 });
    tool.onMouseMove({ x: 176, y: 120, button: 0 });
    tool.onMouseUp({ x: 176, y: 120, button: 0 });

    const moved = useEntityStore.getState().byId[equipment.id];
    const connectedRun = useEntityStore.getState().byId[run.id];

    expect(moved?.type).toBe('equipment');
    if (moved?.type !== 'equipment') {
      throw new Error('Expected equipment');
    }
    expect(moved.transform.x).toBe(140);
    expect(moved.transform.y).toBe(100);
    expect(
      moved.props.connectionPorts?.find((port) => port.id === 'supply-1')?.connectedDuctId
    ).toBe(run.id);
    expect(connectedRun?.type).toBe('duct_run');
    if (connectedRun?.type !== 'duct_run') {
      throw new Error('Expected duct_run');
    }
    expect(connectedRun.props.connectedFrom).toBe(equipment.id);
  });

  it('renders a stronger blue magnetic preview as the endpoint gets closer', () => {
    const tool = new SelectTool() as unknown as {
      state: Record<string, unknown>;
      render: (context: { ctx: CanvasRenderingContext2D; zoom: number }) => void;
    };
    const strokeStyles: string[] = [];
    const ctx = {
      save: () => undefined,
      restore: () => undefined,
      beginPath: () => undefined,
      arc: () => undefined,
      fill: () => undefined,
      stroke: () => undefined,
      set fillStyle(_value: string) {},
      set strokeStyle(value: string) {
        strokeStyles.push(value);
      },
      set lineWidth(_value: number) {},
    };

    tool.state = {
      mode: 'dragging',
      liveSnapTargets: {
        start: {
          snapType: 'duct_endpoint',
          point: { x: 100, y: 100 },
          distance: MagneticConnectionService.SNAP_TOLERANCE - 1,
        },
        end: {
          snapType: 'duct_endpoint',
          point: { x: 140, y: 100 },
          distance: 1,
        },
      },
    };

    tool.render({ ctx: ctx as unknown as CanvasRenderingContext2D, zoom: 1 });

    const alphas = strokeStyles
      .map((style) => /rgba\(33, 150, 243, ([\d.]+)\)/.exec(style)?.[1])
      .filter((alpha): alpha is string => Boolean(alpha))
      .map(Number);
    expect(alphas).toHaveLength(2);
    expect(alphas[1]).toBeGreaterThan(alphas[0]);
  });

  it('fades out the blue magnetic preview when the endpoint moves far from a target', () => {
    const tool = new SelectTool() as unknown as {
      state: Record<string, unknown>;
      render: (context: { ctx: CanvasRenderingContext2D; zoom: number }) => void;
    };
    const strokeStyles: string[] = [];
    const ctx = {
      save: () => undefined,
      restore: () => undefined,
      beginPath: () => undefined,
      arc: () => undefined,
      fill: () => undefined,
      stroke: () => undefined,
      set fillStyle(_value: string) {},
      set strokeStyle(value: string) {
        strokeStyles.push(value);
      },
      set lineWidth(_value: number) {},
    };

    tool.state = {
      mode: 'dragging',
      liveSnapTargets: {
        start: {
          snapType: 'duct_endpoint',
          point: { x: 100, y: 100 },
          distance: MagneticConnectionService.SNAP_TOLERANCE,
        },
        end: null,
      },
    };

    tool.render({ ctx: ctx as unknown as CanvasRenderingContext2D, zoom: 1 });

    expect(strokeStyles).toHaveLength(0);
  });
});
