import { beforeEach, describe, expect, it, vi } from 'vitest';
import { FittingGenerationService } from '../fittingGeneration';
import type { DetectedConnection } from '../connectionDetection';
import type { UnifiedComponentDefinition } from '@/core/schema/unified-component.schema';
import { useComponentLibraryStoreV2 } from '@/core/store/componentLibraryStoreV2';

vi.mock('@/core/store/componentLibraryStoreV2', () => ({
  useComponentLibraryStoreV2: {
    getState: vi.fn(),
  },
}));

describe('FittingGenerationService', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('maps 90-degree elbow to elbow_90 and passes service rule matching', () => {
    const activeComponent: UnifiedComponentDefinition = {
      id: 'svc-1',
      name: 'Low Pressure Supply',
      category: 'duct',
      type: 'duct',
      systemType: 'supply',
      pressureClass: 'low',
      engineeringProperties: {
        frictionFactor: 0.02,
        maxVelocity: 2500,
        minVelocity: 500,
        maxPressureDrop: 0.1,
      },
      pricing: {
        materialCost: 0,
        laborUnits: 0,
        wasteFactor: 0,
      },
      materials: [
        {
          id: 'mat-1',
          name: 'Galvanized Steel',
          type: 'galvanized_steel',
          cost: 0,
          costUnit: 'linear_foot',
        },
      ],
      customFields: {
        dimensionalConstraints: {
          minDiameter: 4,
          maxDiameter: 24,
          minWidth: 4,
          maxWidth: 60,
          minHeight: 4,
          maxHeight: 60,
          allowedShapes: ['round', 'rectangular'],
        },
        fittingRules: [{ angle: 90, fittingType: 'elbow_90', preference: 1 }],
      },
      isCustom: true,
    };

    vi.mocked(useComponentLibraryStoreV2.getState).mockReturnValue({
      getActiveComponent: () => activeComponent,
    } as ReturnType<typeof useComponentLibraryStoreV2.getState>);

    const connection: DetectedConnection = {
      newDuct: {
        entityId: 'd-new',
        endPoint: 'end',
        position: { x: 100, y: 100 },
        angle: 0,
      },
      existingDuct: {
        entityId: 'd-old',
        endPoint: 'start',
        position: { x: 100, y: 100 },
        angle: 90,
      },
      fittingType: 'elbow',
      angle: 90,
    };

    const fitting = FittingGenerationService.generateFitting(connection);

    expect(fitting).not.toBeNull();
    expect(fitting?.props.fittingType).toBe('elbow_90');
    expect(fitting?.props.autoGenerated).toBe(true);
  });
});
