import { describe, expect, it } from 'vitest';
import { FittingInsertionService } from '../automation/fittingInsertionService';
import type { Duct, Entity, Fitting } from '@/core/schema';

function createMockDuct(
  id: string,
  x: number,
  y: number,
  rotation: number,
  diameter: number,
  lengthFeet = 10
): Duct {
  return {
    id,
    type: 'duct',
    transform: { x, y, rotation, scaleX: 1, scaleY: 1 },
    zIndex: 5,
    createdAt: '2026-01-01T00:00:00.000Z',
    modifiedAt: '2026-01-01T00:00:00.000Z',
    props: {
      name: `Duct ${id}`,
      shape: 'round',
      diameter,
      length: lengthFeet,
      material: 'galvanized',
      airflow: 1000,
      staticPressure: 0.1,
    },
    calculated: {
      area: 113,
      velocity: 1200,
      frictionLoss: 0.05,
    },
  };
}

function createMockAutoInsertedFitting(id: string, inletDuctId?: string, outletDuctId?: string): Fitting {
  return {
    id,
    type: 'fitting',
    transform: { x: 0, y: 0, rotation: 0, scaleX: 1, scaleY: 1 },
    zIndex: 10,
    createdAt: '2026-01-01T00:00:00.000Z',
    modifiedAt: '2026-01-01T00:00:00.000Z',
    props: {
      name: `Fitting ${id}`,
      fittingType: 'elbow_90',
      inletDuctId,
      outletDuctId,
      autoGenerated: true,
      autoInserted: true,
    },
    calculated: {
      equivalentLength: 0,
      pressureLoss: 0,
    },
  };
}

describe('FittingInsertionService', () => {
  it('selects elbow deterministically for 90-degree connection pattern', () => {
    const existing = createMockDuct('existing', 100, 100, 0, 12);
    const newDuct = createMockDuct('new', 220, 100, 90, 12);
    const entities: Record<string, Entity> = {
      existing,
      new: newDuct,
    };

    const first = FittingInsertionService.planAutoInsertForDuct('new', entities);
    const second = FittingInsertionService.planAutoInsertForDuct('new', entities);

    expect(first.insertions).toHaveLength(1);
    expect(second.insertions).toHaveLength(1);
    expect(first.insertions[0]?.props.fittingType).toBe('elbow_90');
    expect(second.insertions[0]?.props.fittingType).toBe('elbow_90');
    expect(first.insertions[0]?.transform.x).toBe(second.insertions[0]?.transform.x);
    expect(first.insertions[0]?.transform.y).toBe(second.insertions[0]?.transform.y);
  });

  it('selects tee deterministically when three ducts meet at one junction', () => {
    const trunk = createMockDuct('trunk', 100, 100, 0, 12);
    const branchA = createMockDuct('branch-a', 220, -20, 90, 12);
    const branchB = createMockDuct('branch-b', 220, 100, 90, 12);
    const entities: Record<string, Entity> = {
      trunk,
      'branch-a': branchA,
      'branch-b': branchB,
    };

    const result = FittingInsertionService.planAutoInsertForDuct('branch-b', entities);

    expect(result.insertions).toHaveLength(1);
    expect(result.insertions[0]?.props.fittingType).toBe('tee');
  });

  it('selects transition deterministically for straight size-change pattern', () => {
    const large = createMockDuct('large', 100, 100, 0, 24);
    const small = createMockDuct('small', 220, 100, 0, 12);
    const entities: Record<string, Entity> = {
      large,
      small,
    };

    const result = FittingInsertionService.planAutoInsertForDuct('small', entities);

    expect(result.insertions).toHaveLength(1);
    expect(result.insertions[0]?.props.fittingType).toBe('reducer');
  });

  it('detects orphan auto-inserted fittings after connected ducts are missing', () => {
    const surviving = createMockDuct('surviving', 100, 100, 0, 12);
    const orphan = createMockAutoInsertedFitting('fit-orphan', 'surviving', 'missing-duct');
    const entities: Record<string, Entity> = {
      surviving,
      'fit-orphan': orphan,
    };

    const orphanIds = FittingInsertionService.detectOrphanFittings(entities);

    expect(orphanIds).toEqual(['fit-orphan']);
  });
});

