import { beforeEach, describe, expect, it, vi } from 'vitest';
import { FittingGenerationService } from '../fittingGeneration';
import type { DetectedConnection } from '../connectionDetection';
import { useServiceStore } from '@/core/store/serviceStore';

vi.mock('@/core/store/serviceStore', () => ({
  useServiceStore: {
    getState: vi.fn(),
  },
}));

describe('FittingGenerationService', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('maps 90-degree elbow to elbow_90 and passes service rule matching', () => {
    vi.mocked(useServiceStore.getState).mockReturnValue({
      activeServiceId: 'svc-1',
      services: {},
      baselineTemplates: [
        {
          id: 'svc-1',
          isTemplate: true,
          name: 'Low Pressure Supply',
          systemType: 'supply',
          material: 'galvanized',
          pressureClass: 'low',
          dimensionalConstraints: {
            minDiameter: 4,
            maxDiameter: 24,
            minWidth: 4,
            maxWidth: 60,
            minHeight: 4,
            maxHeight: 60,
            allowedShapes: ['round', 'rectangular'],
          },
          fittingRules: [{ angle: 90, fittingType: 'elbow_90', preference: 1 }],
          manufacturerPreferences: ['Generic'],
          source: 'baseline',
          color: '#4A90E2',
        },
      ],
    } as ReturnType<typeof useServiceStore.getState>);

    const connection: DetectedConnection = {
      newDuct: {
        entityId: 'd-new',
        endPoint: 'end',
        position: { x: 100, y: 100 },
        angle: 0,
      },
      existingDuct: {
        entityId: 'd-old',
        endPoint: 'start',
        position: { x: 100, y: 100 },
        angle: 90,
      },
      fittingType: 'elbow',
      angle: 90,
    };

    const fitting = FittingGenerationService.generateFitting(connection);

    expect(fitting).not.toBeNull();
    expect(fitting?.props.fittingType).toBe('elbow_90');
    expect(fitting?.props.autoGenerated).toBe(true);
  });
});

