import type { Fitting } from '@/core/schema';
import {
  DEFAULT_FITTING_PROPS,
  DEFAULT_FITTING_CALCULATED,
  type FittingProps,
  type FittingType,
} from '@/core/schema/fitting.schema';

/**
 * Counter for auto-incrementing fitting names
 */
let fittingCounter = 1;

/**
 * Reset the fitting counter (useful for testing)
 */
export function resetFittingCounter(): void {
  fittingCounter = 1;
}

/**
 * Get the next fitting number and increment counter
 */
export function getNextFittingNumber(): number {
  return fittingCounter++;
}

/**
 * Create a new fitting entity with default values
 */
export function createFitting(
  fittingType: FittingType,
  overrides?: Partial<{
    name: string;
    x: number;
    y: number;
    rotation: number;
    angle: number;
    inletDuctId: string;
    outletDuctId: string;
    serviceId: string;
    catalogItemId: string;
    autoGenerated: boolean;
    autoInserted: boolean;
    manualOverride: boolean;
    connectionPoints: Array<{ ductId: string; pointIndex?: number }>;
    transitionData: FittingProps['transitionData'];
    engineeringSystem: FittingProps['engineeringSystem'];
    backpressureLimit: number;
    thermalExpansionJointRequired: boolean;
    weldedAccessRequired: boolean;
    greaseRated: boolean;
    wallType: 'single' | 'double';
    condensateDrainRequired: boolean;
  }>
): Fitting {
  const fittingNumber = getNextFittingNumber();
  const now = new Date().toISOString();
  const typeDefaults = DEFAULT_FITTING_PROPS[fittingType];

  const props = {
    name: overrides?.name ?? `${FITTING_TYPE_LABELS[fittingType]} ${fittingNumber}`,
    engineeringSystem: overrides?.engineeringSystem ?? typeDefaults.engineeringSystem ?? 'standard_duct',
    fittingType,
    angle: overrides?.angle ?? typeDefaults.angle,
    inletDuctId: overrides?.inletDuctId,
    outletDuctId: overrides?.outletDuctId,
    serviceId: overrides?.serviceId,
    catalogItemId: overrides?.catalogItemId,
    autoGenerated: overrides?.autoGenerated ?? false,
    autoInserted: overrides?.autoInserted ?? false,
    manualOverride: overrides?.manualOverride ?? typeDefaults.manualOverride ?? false,
    connectionPoints: overrides?.connectionPoints,
    transitionData: overrides?.transitionData,
    ...(overrides?.backpressureLimit !== undefined ? { backpressureLimit: overrides.backpressureLimit } : {}),
    ...(overrides?.thermalExpansionJointRequired !== undefined
      ? { thermalExpansionJointRequired: overrides.thermalExpansionJointRequired }
      : {}),
    ...(overrides?.weldedAccessRequired !== undefined
      ? { weldedAccessRequired: overrides.weldedAccessRequired }
      : {}),
    ...(overrides?.greaseRated !== undefined ? { greaseRated: overrides.greaseRated } : {}),
    ...(overrides?.wallType ? { wallType: overrides.wallType } : {}),
    ...(overrides?.condensateDrainRequired !== undefined
      ? { condensateDrainRequired: overrides.condensateDrainRequired }
      : {}),
  };

  return {
    id: crypto.randomUUID(),
    type: 'fitting',
    transform: {
      x: overrides?.x ?? 0,
      y: overrides?.y ?? 0,
      elevation: 0,
      rotation: overrides?.rotation ?? 0,
      scaleX: 1,
      scaleY: 1,
    },
    zIndex: 10, // Fittings should render above ducts
    createdAt: now,
    modifiedAt: now,
    props,
    calculated: { ...DEFAULT_FITTING_CALCULATED },
  };
}

/**
 * Labels for fitting types (UI display)
 */
export const FITTING_TYPE_LABELS: Record<FittingType, string> = {
  elbow_90: '90° Elbow',
  elbow_45: '45° Elbow',
  tee: 'Tee',
  reducer: 'Reducer',
  cap: 'Cap',
  transition_square_to_round: 'Square to Round Transition',
  reducer_tapered: 'Tapered Reducer',
  reducer_eccentric: 'Eccentric Reducer',
  wye: 'Wye',
  elbow_mitered: 'Mitered Elbow',
  end_boot: 'End Boot',
};

export default createFitting;
