import type { ProjectFile, Room, Duct, Equipment } from '@/core/schema';
import { generateBillOfMaterials, type BomItem } from './csv';

/**
 * PDF export options
 */
export interface PdfExportOptions {
  /** Include cover page (default: true) */
  includeCoverPage?: boolean;
  /** Include room schedules (default: true) */
  includeRoomSchedules?: boolean;
  /** Include duct schedules (default: true) */
  includeDuctSchedules?: boolean;
  /** Include equipment schedules (default: true) */
  includeEquipmentSchedules?: boolean;
  /** Include bill of materials (default: true) */
  includeBom?: boolean;
  /** Include calculation summaries (default: true) */
  includeCalculations?: boolean;
}

/**
 * Generate HTML for cover page
 */
function generateCoverPageHtml(project: ProjectFile): string {
  const createdDate = new Date(project.createdAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const modifiedDate = new Date(project.modifiedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return `
    <div class="cover-page">
      <div class="cover-content">
        <h1>${escapeHtml(project.projectName)}</h1>
        ${project.projectNumber ? `<p class="project-number">Project #: ${escapeHtml(project.projectNumber)}</p>` : ''}
        ${project.clientName ? `<p class="client-name">Client: ${escapeHtml(project.clientName)}</p>` : ''}
        <div class="cover-meta">
          <p>Created: ${createdDate}</p>
          <p>Last Modified: ${modifiedDate}</p>
        </div>
        <div class="cover-footer">
          <p>HVAC Design Document</p>
          <p>Generated by SizeWise HVAC Canvas</p>
        </div>
      </div>
    </div>
  `;
}

/**
 * Generate HTML for room schedule
 */
function generateRoomScheduleHtml(entities: ProjectFile['entities']): string {
  const rooms: Room[] = [];
  for (const id of entities.allIds) {
    const entity = entities.byId[id];
    if (entity?.type === 'room') {
      rooms.push(entity as Room);
    }
  }

  if (rooms.length === 0) {
    return '<p class="no-data">No rooms in project</p>';
  }

  const rows = rooms
    .map(
      (room) => `
    <tr>
      <td>${escapeHtml(room.name)}</td>
      <td>${room.props.width}"</td>
      <td>${room.props.height}"</td>
      <td>${room.props.ceilingHeight}"</td>
      <td>${escapeHtml(room.props.roomType)}</td>
      <td>${room.props.occupancy ?? '-'}</td>
      <td>${room.calculated?.area?.toFixed(1) ?? '-'} sq ft</td>
      <td>${room.calculated?.volume?.toFixed(1) ?? '-'} cu ft</td>
      <td>${room.calculated?.requiredCfm?.toFixed(0) ?? '-'} CFM</td>
    </tr>
  `
    )
    .join('');

  return `
    <section class="schedule">
      <h2>Room Schedule</h2>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Width</th>
            <th>Height</th>
            <th>Ceiling</th>
            <th>Type</th>
            <th>Occupancy</th>
            <th>Area</th>
            <th>Volume</th>
            <th>Required CFM</th>
          </tr>
        </thead>
        <tbody>
          ${rows}
        </tbody>
      </table>
    </section>
  `;
}

/**
 * Generate HTML for duct schedule
 */
function generateDuctScheduleHtml(entities: ProjectFile['entities']): string {
  const ducts: Duct[] = [];
  for (const id of entities.allIds) {
    const entity = entities.byId[id];
    if (entity?.type === 'duct') {
      ducts.push(entity as Duct);
    }
  }

  if (ducts.length === 0) {
    return '<p class="no-data">No ducts in project</p>';
  }

  const rows = ducts
    .map(
      (duct) => `
    <tr>
      <td>${escapeHtml(duct.name)}</td>
      <td>${duct.props.shape}</td>
      <td>${
        duct.props.shape === 'round'
          ? `${duct.props.diameter}" dia`
          : `${duct.props.width}" x ${duct.props.height}"`
      }</td>
      <td>${duct.props.length} ft</td>
      <td>${escapeHtml(duct.props.material)}</td>
      <td>${duct.props.cfm} CFM</td>
      <td>${duct.calculated?.velocity?.toFixed(0) ?? '-'} FPM</td>
      <td>${duct.calculated?.pressureDrop?.toFixed(3) ?? '-'} in.wg</td>
    </tr>
  `
    )
    .join('');

  return `
    <section class="schedule">
      <h2>Duct Schedule</h2>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Shape</th>
            <th>Size</th>
            <th>Length</th>
            <th>Material</th>
            <th>CFM</th>
            <th>Velocity</th>
            <th>Pressure Drop</th>
          </tr>
        </thead>
        <tbody>
          ${rows}
        </tbody>
      </table>
    </section>
  `;
}

/**
 * Generate HTML for equipment schedule
 */
function generateEquipmentScheduleHtml(entities: ProjectFile['entities']): string {
  const equipment: Equipment[] = [];
  for (const id of entities.allIds) {
    const entity = entities.byId[id];
    if (entity?.type === 'equipment') {
      equipment.push(entity as Equipment);
    }
  }

  if (equipment.length === 0) {
    return '<p class="no-data">No equipment in project</p>';
  }

  const rows = equipment
    .map(
      (eq) => `
    <tr>
      <td>${escapeHtml(eq.name)}</td>
      <td>${escapeHtml(eq.props.equipmentType.replace(/_/g, ' '))}</td>
      <td>${escapeHtml(eq.props.manufacturer ?? '-')}</td>
      <td>${escapeHtml(eq.props.model ?? '-')}</td>
      <td>${eq.props.capacity ? `${eq.props.capacity} ${eq.props.capacityUnit ?? ''}` : '-'}</td>
      <td>${eq.props.width}" x ${eq.props.height}"</td>
    </tr>
  `
    )
    .join('');

  return `
    <section class="schedule">
      <h2>Equipment Schedule</h2>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Manufacturer</th>
            <th>Model</th>
            <th>Capacity</th>
            <th>Size</th>
          </tr>
        </thead>
        <tbody>
          ${rows}
        </tbody>
      </table>
    </section>
  `;
}

/**
 * Generate HTML for Bill of Materials
 */
function generateBomHtml(entities: ProjectFile['entities']): string {
  const items = generateBillOfMaterials(entities);

  if (items.length === 0) {
    return '<p class="no-data">No items in bill of materials</p>';
  }

  const rows = items
    .map(
      (item) => `
    <tr>
      <td>${item.itemNumber}</td>
      <td>${escapeHtml(item.type)}</td>
      <td>${escapeHtml(item.name)}</td>
      <td>${escapeHtml(item.description)}</td>
      <td>${item.quantity}</td>
      <td>${escapeHtml(item.unit)}</td>
      <td>${escapeHtml(item.specifications)}</td>
    </tr>
  `
    )
    .join('');

  return `
    <section class="schedule bom">
      <h2>Bill of Materials</h2>
      <table>
        <thead>
          <tr>
            <th>Item #</th>
            <th>Type</th>
            <th>Name</th>
            <th>Description</th>
            <th>Qty</th>
            <th>Unit</th>
            <th>Specifications</th>
          </tr>
        </thead>
        <tbody>
          ${rows}
        </tbody>
      </table>
    </section>
  `;
}

/**
 * Generate HTML for calculation summary
 */
function generateCalculationSummaryHtml(entities: ProjectFile['entities']): string {
  let totalRoomArea = 0;
  let totalRoomVolume = 0;
  let totalRequiredCfm = 0;
  let roomCount = 0;

  let totalDuctLength = 0;
  let ductCount = 0;

  let equipmentCount = 0;

  for (const id of entities.allIds) {
    const entity = entities.byId[id];
    if (entity?.type === 'room') {
      const room = entity as Room;
      roomCount++;
      if (room.calculated?.area) totalRoomArea += room.calculated.area;
      if (room.calculated?.volume) totalRoomVolume += room.calculated.volume;
      if (room.calculated?.requiredCfm) totalRequiredCfm += room.calculated.requiredCfm;
    } else if (entity?.type === 'duct') {
      const duct = entity as Duct;
      ductCount++;
      totalDuctLength += duct.props.length;
    } else if (entity?.type === 'equipment') {
      equipmentCount++;
    }
  }

  return `
    <section class="summary">
      <h2>Calculation Summary</h2>
      <div class="summary-grid">
        <div class="summary-card">
          <h3>Rooms</h3>
          <ul>
            <li>Total Rooms: ${roomCount}</li>
            <li>Total Area: ${totalRoomArea.toFixed(1)} sq ft</li>
            <li>Total Volume: ${totalRoomVolume.toFixed(1)} cu ft</li>
            <li>Total Required CFM: ${totalRequiredCfm.toFixed(0)} CFM</li>
          </ul>
        </div>
        <div class="summary-card">
          <h3>Ductwork</h3>
          <ul>
            <li>Total Ducts: ${ductCount}</li>
            <li>Total Length: ${totalDuctLength.toFixed(1)} ft</li>
          </ul>
        </div>
        <div class="summary-card">
          <h3>Equipment</h3>
          <ul>
            <li>Total Equipment: ${equipmentCount}</li>
          </ul>
        </div>
      </div>
    </section>
  `;
}

/**
 * Escape HTML special characters
 */
function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/**
 * Get CSS styles for PDF
 */
function getPdfStyles(): string {
  return `
    <style>
      * {
        box-sizing: border-box;
        margin: 0;
        padding: 0;
      }

      body {
        font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
        font-size: 11pt;
        line-height: 1.4;
        color: #333;
      }

      .cover-page {
        page-break-after: always;
        height: 100vh;
        display: flex;
        align-items: center;
        justify-content: center;
        text-align: center;
      }

      .cover-content h1 {
        font-size: 28pt;
        margin-bottom: 1rem;
        color: #1976d2;
      }

      .project-number, .client-name {
        font-size: 14pt;
        color: #666;
        margin: 0.5rem 0;
      }

      .cover-meta {
        margin-top: 3rem;
        font-size: 10pt;
        color: #999;
      }

      .cover-footer {
        margin-top: 6rem;
        font-size: 10pt;
        color: #666;
      }

      .schedule {
        page-break-inside: avoid;
        margin: 2rem 0;
      }

      h2 {
        font-size: 16pt;
        color: #1976d2;
        margin-bottom: 1rem;
        padding-bottom: 0.5rem;
        border-bottom: 2px solid #e0e0e0;
      }

      table {
        width: 100%;
        border-collapse: collapse;
        font-size: 9pt;
      }

      th, td {
        border: 1px solid #ddd;
        padding: 6px 8px;
        text-align: left;
      }

      th {
        background-color: #f5f5f5;
        font-weight: 600;
      }

      tr:nth-child(even) {
        background-color: #fafafa;
      }

      .no-data {
        color: #999;
        font-style: italic;
        padding: 1rem;
      }

      .summary {
        margin: 2rem 0;
      }

      .summary-grid {
        display: flex;
        gap: 1rem;
        flex-wrap: wrap;
      }

      .summary-card {
        flex: 1;
        min-width: 200px;
        background: #f5f5f5;
        padding: 1rem;
        border-radius: 8px;
      }

      .summary-card h3 {
        font-size: 12pt;
        margin-bottom: 0.5rem;
        color: #333;
      }

      .summary-card ul {
        list-style: none;
        font-size: 10pt;
      }

      .summary-card li {
        padding: 0.25rem 0;
      }

      @media print {
        .cover-page {
          height: 100vh;
        }

        .schedule {
          page-break-inside: avoid;
        }

        body {
          print-color-adjust: exact;
          -webkit-print-color-adjust: exact;
        }
      }
    </style>
  `;
}

/**
 * Generate complete PDF HTML document
 */
export function generatePdfHtml(
  project: ProjectFile,
  options: PdfExportOptions = {}
): string {
  const {
    includeCoverPage = true,
    includeRoomSchedules = true,
    includeDuctSchedules = true,
    includeEquipmentSchedules = true,
    includeBom = true,
    includeCalculations = true,
  } = options;

  const sections: string[] = [];

  if (includeCoverPage) {
    sections.push(generateCoverPageHtml(project));
  }

  if (includeCalculations) {
    sections.push(generateCalculationSummaryHtml(project.entities));
  }

  if (includeRoomSchedules) {
    sections.push(generateRoomScheduleHtml(project.entities));
  }

  if (includeDuctSchedules) {
    sections.push(generateDuctScheduleHtml(project.entities));
  }

  if (includeEquipmentSchedules) {
    sections.push(generateEquipmentScheduleHtml(project.entities));
  }

  if (includeBom) {
    sections.push(generateBomHtml(project.entities));
  }

  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8">
        <title>${escapeHtml(project.projectName)} - HVAC Design Document</title>
        ${getPdfStyles()}
      </head>
      <body>
        ${sections.join('\n')}
      </body>
    </html>
  `;
}

/**
 * Open print dialog for PDF export
 */
export function printProjectAsPdf(project: ProjectFile, options: PdfExportOptions = {}): void {
  const html = generatePdfHtml(project, options);

  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    console.error('Failed to open print window. Please allow popups.');
    return;
  }

  printWindow.document.write(html);
  printWindow.document.close();

  // Wait for content to load, then print
  printWindow.onload = () => {
    setTimeout(() => {
      printWindow.print();
    }, 250);
  };
}

/**
 * Download PDF HTML as an HTML file (alternative to print)
 */
export function downloadPdfHtml(project: ProjectFile, options: PdfExportOptions = {}): void {
  const html = generatePdfHtml(project, options);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${project.projectName.replace(/\s+/g, '_')}_report.html`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
